/**
 * Generates documentation FROM THE LIVE SCHEMA so it can never drift from the migrations:
 *   docs/database/erd.mermaid          Mermaid ER diagram (keys + a few business columns)
 *   docs/database/DATA-DICTIONARY.md   every table, column, type, default, constraint
 * Usage: DATABASE_URL=... pnpm db:erd
 */
import { config as loadDotenv } from 'dotenv';
loadDotenv({ quiet: true });
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import pg from 'pg';

const outDir = path.resolve(import.meta.dirname, '../../../docs/database');
const url = process.env.DATABASE_URL;
if (!url) throw new Error('DATABASE_URL is not set');

const client = new pg.Client({ connectionString: url });
await client.connect();

interface Col { table: string; name: string; type: string; notNull: boolean; def: string | null }
interface Con { table: string; kind: 'p' | 'f' | 'u'; cols: string[]; refTable: string | null; refCols: string[] | null; def: string }

const cols = (await client.query<{ table: string; name: string; type: string; not_null: boolean; def: string | null }>(`
  SELECT c.relname AS "table", a.attname AS name, format_type(a.atttypid, a.atttypmod) AS type, a.attnotnull AS not_null,
         pg_get_expr(d.adbin, d.adrelid) AS def
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
   WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relname <> 'schema_migrations'
   ORDER BY c.relname, a.attnum`)).rows.map((r): Col => ({ table: r.table, name: r.name, type: r.type, notNull: r.not_null, def: r.def }));

const cons = (await client.query<{ table: string; kind: 'p' | 'f' | 'u'; cols: string[]; ref_table: string | null; ref_cols: string[] | null; def: string }>(`
  SELECT c.relname AS "table", con.contype AS kind,
         (SELECT array_agg(att.attname::text ORDER BY k.ord) FROM unnest(con.conkey) WITH ORDINALITY k(num, ord)
            JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = k.num) AS cols,
         fc.relname AS ref_table,
         (SELECT array_agg(att.attname::text ORDER BY k.ord) FROM unnest(con.confkey) WITH ORDINALITY k(num, ord)
            JOIN pg_attribute att ON att.attrelid = con.confrelid AND att.attnum = k.num) AS ref_cols,
         pg_get_constraintdef(con.oid) AS def
    FROM pg_constraint con JOIN pg_class c ON c.oid = con.conrelid JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_class fc ON fc.oid = con.confrelid
   WHERE n.nspname = 'public' AND con.contype IN ('p','f','u') AND c.relname <> 'schema_migrations'
   ORDER BY c.relname, con.conname`)).rows.map((r): Con => ({ table: r.table, kind: r.kind, cols: r.cols, refTable: r.ref_table, refCols: r.ref_cols, def: r.def }));

const tableInfo = new Map((await client.query<{ table: string; comment: string | null }>(`
  SELECT c.relname AS "table", obj_description(c.oid) AS comment FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relname <> 'schema_migrations'`)).rows.map((r) => [r.table, r.comment ?? '']));

const triggers = (await client.query<{ table: string; name: string }>(`
  SELECT c.relname AS "table", t.tgname AS name FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND NOT t.tgisinternal`)).rows;
await client.end();

const tables = [...tableInfo.keys()].sort();
const colsOf = (t: string) => cols.filter((c) => c.table === t);
const fks = cons.filter((c) => c.kind === 'f');
const pkOf = (t: string) => new Set(cons.find((c) => c.table === t && c.kind === 'p')?.cols ?? []);
const fkColsOf = (t: string) => new Set(fks.filter((f) => f.table === t).flatMap((f) => f.cols));

// ---------- Mermaid ----------
const AUDIT_USER_COLS = new Set(['created_by', 'changed_by', 'settled_by', 'collected_by']);
const EXTRA = new Set(['status', 'order_number', 'public_code', 'sku', 'code', 'txn_type', 'method', 'channel', 'movement_type', 'template_key', 'total', 'key']);
const mtype = (t: string) => {
  if (t.startsWith('timestamp')) return 'timestamptz';
  if (t.startsWith('numeric')) return 'numeric';
  if (t.startsWith('character(')) return 'char';
  if (t === 'integer') return 'int';
  if (t === 'boolean') return 'bool';
  if (t.endsWith('[]')) return 'text_array';
  return t.replace(/[^a-z0-9_]/gi, '');
};

const lines: string[] = [
  'erDiagram',
  '  %% Generated by `pnpm db:erd` from the live schema. Do not edit by hand.',
  '  %% Every operational table also has branch_id -> branches (composite FKs keep parent and child in the same branch).',
];
for (const t of tables) {
  const pk = pkOf(t); const fk = fkColsOf(t);
  lines.push(`  ${t} {`);
  for (const c of colsOf(t)) {
    if (!(pk.has(c.name) || fk.has(c.name) || EXTRA.has(c.name))) continue;
    const marks = [pk.has(c.name) ? 'PK' : '', fk.has(c.name) ? 'FK' : ''].filter(Boolean).join(',');
    lines.push(`    ${mtype(c.type)} ${c.name}${marks ? ' ' + marks : ''}`);
  }
  lines.push('  }');
}
const ROOTS_UNDER_BRANCH = new Set(['users', 'customers', 'products', 'inventory_items', 'orders']);
const seen = new Set<string>();
for (const f of fks) {
  if (!f.refTable) continue;
  const own = f.cols.filter((c) => c !== 'branch_id');
  if (own.length === 0 && !(f.refTable === 'branches' && ROOTS_UNDER_BRANCH.has(f.table))) continue;
  if (f.refTable === 'branches' && !ROOTS_UNDER_BRANCH.has(f.table)) continue;
  const col = own[0] ?? 'branch_id';
  if (AUDIT_USER_COLS.has(col)) continue;
  const key = `${f.refTable}>${f.table}:${col}`;
  if (seen.has(key)) continue;
  seen.add(key);
  const optional = own.length > 0 && own.some((c) => !colsOf(f.table).find((x) => x.name === c)?.notNull);
  lines.push(`  ${f.refTable} ${optional ? '|o' : '||'}--o{ ${f.table} : "${col}"`);
}
await mkdir(outDir, { recursive: true });
await writeFile(path.join(outDir, 'erd.mermaid'), lines.join('\n') + '\n');

// ---------- Data dictionary ----------
const md: string[] = ['# Data dictionary', '', '_Generated by `pnpm db:erd` from the live schema._', '',
  'Sync classes: **syncable** = has server-managed `updated_at`/`row_version` (pulled by offline clients); **append-only** = UPDATE/DELETE are rejected by a trigger; **server-only** = never sent to clients.', ''];
for (const t of tables) {
  const tg = triggers.filter((x) => x.table === t).map((x) => x.name);
  const cls = tg.includes('trg_append_only') ? 'append-only' : tg.includes('trg_sync_touch') ? 'syncable' : 'server-only';
  md.push(`## ${t}`, '', `${tableInfo.get(t) ?? ''}`, '', `Sync class: **${cls}**`, '', '| Column | Type | Null | Default | Notes |', '| --- | --- | --- | --- | --- |');
  const pk = pkOf(t);
  for (const c of colsOf(t)) {
    const notes: string[] = [];
    if (pk.has(c.name)) notes.push('PK');
    for (const f of fks.filter((x) => x.table === t && x.cols.includes(c.name))) {
      if (c.name === 'branch_id' && f.cols.length > 1) continue;   // composite branch guard: described once in the header
      const i = f.cols.indexOf(c.name);
      notes.push(`FK → ${f.refTable}.${f.refCols?.[i]}${f.cols.length > 1 ? ' (composite with branch_id)' : ''}`);
    }
    md.push(`| \`${c.name}\` | ${c.type} | ${c.notNull ? 'no' : 'yes'} | ${c.def ? '`' + c.def.replace(/\|/g, '\\|') + '`' : ''} | ${notes.join('; ')} |`);
  }
  const uniques = cons.filter((c) => c.table === t && c.kind === 'u' && c.cols.join() !== 'id,branch_id');
  if (uniques.length) md.push('', 'Unique: ' + uniques.map((u) => '`' + u.def.replace('UNIQUE ', '') + '`').join(', '));
  md.push('');
}
await writeFile(path.join(outDir, 'DATA-DICTIONARY.md'), md.join('\n'));
console.log(`wrote ${tables.length} tables → docs/database/erd.mermaid, docs/database/DATA-DICTIONARY.md`);
