import { copyFile, mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Where pictures live. One shop on one server: plain files next to the database are simplest, fastest and are
 * backed up together with it. The interface is small so an object store can replace it later without touching callers.
 */
export interface MediaStorage {
  put(key: string, data: Buffer): Promise<void>;
  /** Moves an already-written file (a large upload) into storage without reading it into memory. */
  putFile(key: string, sourcePath: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  /** Where a stored file lives on disk, for streaming it back; null if it is gone. */
  pathOf(key: string): Promise<string | null>;
  remove(key: string): Promise<void>;
}

/** Keys are generated by the server, never taken from a request, but they are still checked before touching disk. */
const SAFE_KEY = /^((originals|public)\/[0-9a-f-]{36}(-\d{2,4})?\.(jpg|png|webp)|designs\/[0-9a-f-]{36}\.(pdf|jpg|png|tiff|psd|zip)|proofs\/[0-9a-f-]{36}\.(pdf|jpg|png))$/;

export function assertSafeKey(key: string): void {
  if (!SAFE_KEY.test(key)) throw new Error(`unsafe media key: ${key}`);
}

export function localDiskStorage(rootDir: string): MediaStorage {
  const root = path.resolve(rootDir);
  const fileFor = (key: string) => {
    assertSafeKey(key);
    const full = path.resolve(root, key);
    if (!full.startsWith(root + path.sep)) throw new Error(`media key escapes the storage directory: ${key}`);
    return full;
  };
  return {
    async put(key, data) {
      const file = fileFor(key);
      await mkdir(path.dirname(file), { recursive: true });
      await writeFile(file, data);
    },
    async putFile(key, sourcePath) {
      const file = fileFor(key);
      await mkdir(path.dirname(file), { recursive: true });
      // rename is instant on the same disk; across disks (a temp dir elsewhere) fall back to copy + delete.
      await rename(sourcePath, file).catch(async () => { await copyFile(sourcePath, file); await rm(sourcePath, { force: true }); });
    },
    async pathOf(key) {
      const file = fileFor(key);
      return stat(file).then(() => file, () => null);
    },
    async get(key) {
      try { return await readFile(fileFor(key)); } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
      }
    },
    async remove(key) {
      await rm(fileFor(key), { force: true });
    },
  };
}
